spring:
  redis:
    host: 192.168.1.11
    database: 2
  elasticsearch:
    uris:
      - http://192.168.1.13:9200

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: TRACE


admin4j:
  xss:
    match-pattern: 1
    ignore-uris:
      - /xss/form-ignore/?
    include-uris:
      - /xss/form-include/?
    ignore-param:
      - gender
  oss:
    endpoint: "http://192.168.1.13:9901"
    region: cn-east-1
    access-key: 4NdsQG6g6hzJfwko
    secret-key: zeSSPz3WC3Wn4zBZsYtxK9YXhZ7Hjnnv
    enable: true
    default-bucket-name: oss-template

  zookeeper:
    connect-string: 192.168.1.13:2181,192.168.1.13:2182,192.168.1.13:2183
    namespace: D_LOCK
